<?php

namespace App\Helpers;

class PekerjaanHelper
{
    public function getPekerjaan()
    {
        $datas = [
            array("val0" => "1", "val1" => "1", "val2" => "Belum/ Tidak Bekerja", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "2", "val1" => "2", "val2" => "Mengurus Rumah Tangga", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "3", "val1" => "3", "val2" => "Pelajar/ Mahasiswa", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "4", "val1" => "4", "val2" => "Pensiunan", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "5", "val1" => "5", "val2" => "Pegawai Negeri Sipil", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "6", "val1" => "6", "val2" => "Tentara Nasional Indonesia", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "7", "val1" => "7", "val2" => "Kepolisisan RI", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "8", "val1" => "8", "val2" => "Perdagangan", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "9", "val1" => "9", "val2" => "Petani/ Pekebun", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "10", "val1" => "10", "val2" => "Peternak", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "11", "val1" => "11", "val2" => "Nelayan/ Perikanan", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "12", "val1" => "12", "val2" => "Industri", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "13", "val1" => "13", "val2" => "Konstruksi", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "14", "val1" => "14", "val2" => "Transportasi", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "15", "val1" => "15", "val2" => "Karyawan Swasta", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "16", "val1" => "16", "val2" => "Karyawan BUMN", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "17", "val1" => "17", "val2" => "Karyawan BUMD", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "18", "val1" => "18", "val2" => "Karyawan Honorer", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "19", "val1" => "19", "val2" => "Buruh Harian Lepas", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "20", "val1" => "20", "val2" => "Buruh Tani/ Perkebunan", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "21", "val1" => "21", "val2" => "Buruh Nelayan/ Perikanan", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "22", "val1" => "22", "val2" => "Buruh Peternakan", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "23", "val1" => "23", "val2" => "Pembantu Rumah Tangga", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "24", "val1" => "24", "val2" => "Tukang Cukur", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "25", "val1" => "25", "val2" => "Tukang Listrik", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "26", "val1" => "26", "val2" => "Tukang Batu", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "27", "val1" => "27", "val2" => "Tukang Kayu", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "28", "val1" => "28", "val2" => "Tukang Sol Sepatu", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "29", "val1" => "29", "val2" => "Tukang Las/ Pandai Besi", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "30", "val1" => "30", "val2" => "Tukang Jahit", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "31", "val1" => "31", "val2" => "Tukang Gigi", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "32", "val1" => "32", "val2" => "Penata Rias", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "33", "val1" => "33", "val2" => "Penata Busana", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "34", "val1" => "34", "val2" => "Penata Rambut", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "35", "val1" => "35", "val2" => "Mekanik", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "36", "val1" => "36", "val2" => "Seniman", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "37", "val1" => "37", "val2" => "Tabib", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "38", "val1" => "38", "val2" => "Paraji", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "39", "val1" => "39", "val2" => "Perancang Busana", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "40", "val1" => "40", "val2" => "Penterjemah", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "41", "val1" => "41", "val2" => "Imam Masjid", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "42", "val1" => "42", "val2" => "Pendeta", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "43", "val1" => "43", "val2" => "Pastor", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "44", "val1" => "44", "val2" => "Wartawan", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "45", "val1" => "45", "val2" => "Ustadz/ Mubaligh", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "46", "val1" => "46", "val2" => "Juru Masak", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "47", "val1" => "47", "val2" => "Promotor Acara", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "48", "val1" => "48", "val2" => "Anggota DPR-RI", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "49", "val1" => "49", "val2" => "Anggota DPD", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "50", "val1" => "50", "val2" => "Anggota BPK", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "51", "val1" => "51", "val2" => "Presiden", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "52", "val1" => "52", "val2" => "Wakil Presiden", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "53", "val1" => "53", "val2" => "Anggota Mahkamah Konstitusi", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "54", "val1" => "54", "val2" => "Anggota Kabinet/ Kementerian", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "55", "val1" => "55", "val2" => "Duta Besar", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "56", "val1" => "56", "val2" => "Gubernur", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "57", "val1" => "57", "val2" => "Wakil Gubernur", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "58", "val1" => "58", "val2" => "Bupati", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "59", "val1" => "59", "val2" => "Wakil Bupati", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "60", "val1" => "60", "val2" => "Walikota", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "61", "val1" => "61", "val2" => "Wakil Walikota", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "62", "val1" => "62", "val2" => "Anggota DPRD Provinsi", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "63", "val1" => "63", "val2" => "Anggota DPRD Kabupaten/ Kota", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "64", "val1" => "64", "val2" => "Dosen", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "65", "val1" => "65", "val2" => "Guru", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "66", "val1" => "66", "val2" => "Pilot", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "67", "val1" => "67", "val2" => "Pengacara", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "68", "val1" => "68", "val2" => "Notaris", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "69", "val1" => "69", "val2" => "Arsitek", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "70", "val1" => "70", "val2" => "Akuntan", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "71", "val1" => "71", "val2" => "Konsultan", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "72", "val1" => "72", "val2" => "Dokter", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "73", "val1" => "73", "val2" => "Bidan", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "74", "val1" => "74", "val2" => "Perawat", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "75", "val1" => "75", "val2" => "Apoteker", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "76", "val1" => "76", "val2" => "Psikiater/ Psikolog", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "77", "val1" => "77", "val2" => "Penyiar Televisi", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "78", "val1" => "78", "val2" => "Penyiar Radio", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "79", "val1" => "79", "val2" => "Pelaut", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "80", "val1" => "80", "val2" => "Peneliti", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "81", "val1" => "81", "val2" => "Sopir", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "82", "val1" => "82", "val2" => "Pialang", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "83", "val1" => "83", "val2" => "Paranormal", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "84", "val1" => "84", "val2" => "Pedagang", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "85", "val1" => "85", "val2" => "Perangkat Desa", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "86", "val1" => "86", "val2" => "Kepala Desa", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "87", "val1" => "87", "val2" => "Biarawati", "val3" => "NULL", "val4" => "NULL"),
            array("val0" => "88", "val1" => "88", "val2" => "Wiraswasta", "val3" => "NULL", "val4" => "NULL")
        ];

        return $datas;
    }
}
